package com.project2.service;



import com.project2.model.Event;
import com.project2.model.Registration;
import com.project2.model.Student;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.mail.MailException;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;

import java.io.UnsupportedEncodingException;
import java.time.format.DateTimeFormatter;
import java.util.Base64;

/**
 * EmailService — Sends HTML emails with QR code attachments using JavaMailSender.
 *
 * Features:
 *  • Beautiful HTML email rendered via Thymeleaf template
 *  • Real QR code generated by ZXing and embedded inline in the email
 *  • @Async so email sending never blocks the HTTP response
 *  • Mock mode: if app.mail.mock-mode=true, logs to console instead of sending
 *  • Safe: exceptions are caught so a mail failure never breaks registration
 */
@Service
public class EmailService {

    private static final Logger log = LoggerFactory.getLogger(EmailService.class);

    @Autowired
    private JavaMailSender mailSender;

    @Autowired
    private TemplateEngine templateEngine;

    @Autowired
    private QRCodeService qrCodeService;

    @Value("${spring.mail.username:noreply@campusevents.com}")
    private String fromEmail;

    @Value("${app.mail.from-name:CampusEvents Team}")
    private String fromName;

    @Value("${app.base-url:http://localhost:8080}")
    private String baseUrl;

    @Value("${app.mail.mock-mode:false}")
    private boolean mockMode;

    // ── Public Entry Point ─────────────────────────────────────────────────────

    /**
     * Sends a "Registration Successful" email to the student.
     * Annotated @Async so it runs in a background thread — the student's
     * browser gets the success response immediately without waiting for email.
     *
     * @param registration  The saved Registration entity (with student + event)
     */
    @Async
    public void sendRegistrationConfirmationEmail(Registration registration) {
        try {
            Student student = registration.getStudent();
            Event   event   = registration.getEvent();

            if (student == null || event == null) {
                log.warn("Cannot send email — registration has null student or event. ID={}",
                         registration.getId());
                return;
            }

            // 1. Build QR code content
            String dateStr = event.getDate() != null
                    ? event.getDate().format(DateTimeFormatter.ofPattern("dd MMMM yyyy"))
                    : "TBD";
            String timeStr = event.getTime() != null
                    ? event.getTime().format(DateTimeFormatter.ofPattern("hh:mm a"))
                    : "";

            String qrContent = qrCodeService.buildQRContent(
                    registration.getId(),
                    student.getName(),
                    student.getEmail(),
                    student.getStudentId(),
                    event.getName(),
                    dateStr + (timeStr.isEmpty() ? "" : " at " + timeStr),
                    event.getVenue()
            );

            // 2. Generate QR code as Base64
            String qrBase64 = qrCodeService.generateQRCodeBase64(qrContent);

            // 3. Build Thymeleaf template context
            Context ctx = new Context();
            ctx.setVariable("studentName",     student.getName());
            ctx.setVariable("studentEmail",    student.getEmail());
            ctx.setVariable("studentId",       student.getStudentId());
            ctx.setVariable("eventName",       event.getName());
            ctx.setVariable("eventDate",       dateStr);
            ctx.setVariable("eventTime",       timeStr);
            ctx.setVariable("eventVenue",      event.getVenue());
            ctx.setVariable("eventDepartment", event.getDepartment());
            ctx.setVariable("eventType",       event.getEventType());
            ctx.setVariable("registrationId",  registration.getId());
            ctx.setVariable("registeredAt",    registration.getRegisteredAt()
                    .format(DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a")));
            ctx.setVariable("eventUrl",        baseUrl + "/events/" + event.getId());
            ctx.setVariable("myEventsUrl",     baseUrl + "/my-events");
            ctx.setVariable("qrBase64",        qrBase64);

            // 4. Render HTML from Thymeleaf template
            String htmlBody = templateEngine.process("email/registration-confirmation", ctx);

            // 5. Send or mock
            if (mockMode) {
                printMockEmail(student.getEmail(), event.getName(), htmlBody, qrContent);
            } else {
                sendHtmlEmail(
                    student.getEmail(),
                    "🎉 Registration Confirmed — " + event.getName(),
                    htmlBody,
                    qrBase64,
                    registration.getId()
                );
            }

        } catch (Exception e) {
            // IMPORTANT: catch everything so email failure never breaks registration
            log.error("Failed to send registration email for registration ID={}. Error: {}",
                      registration.getId(), e.getMessage(), e);
        }
    }

    // ── Private Helpers ────────────────────────────────────────────────────────

    /**
     * Builds and sends the MIME email with inline QR code image.
     */
    private void sendHtmlEmail(String toEmail,
                                String subject,
                                String htmlBody,
                                String qrBase64,
                                Long registrationId) throws MessagingException {

        MimeMessage message = mailSender.createMimeMessage();

        // multipart=true enables attachments/inline images
        MimeMessageHelper helper = new MimeMessageHelper(message, true, "UTF-8");

        try {
            helper.setFrom(fromEmail, fromName);
        } catch (UnsupportedEncodingException e) {
            // fallback — set without display name
            helper.setFrom(fromEmail);
        }
        helper.setTo(toEmail);
        helper.setSubject(subject);
        helper.setText(htmlBody, true); // true = HTML

        // Embed QR code as inline image with Content-ID "qrcode"
        // The template references it as <img src="cid:qrcode">
        byte[] qrBytes = Base64.getDecoder().decode(qrBase64);
        helper.addInline("qrcode", new ByteArrayResource(qrBytes), "image/png");

        try {
            mailSender.send(message);
            log.info("✅ Registration confirmation email sent to: {} (reg ID={})",
                     toEmail, registrationId);
        } catch (MailException e) {
            log.error("❌ Failed to send email to {}: {}", toEmail, e.getMessage());
            throw e;
        }
    }

    /**
     * Mock mode: prints a formatted email summary to the console.
     * Useful when SMTP is not configured — you can still verify the feature works.
     */
    private void printMockEmail(String toEmail, String eventName,
                                 String htmlBody, String qrContent) {
        log.info("\n");
        log.info("╔══════════════════════════════════════════════════════╗");
        log.info("║         MOCK EMAIL — Registration Confirmation       ║");
        log.info("╠══════════════════════════════════════════════════════╣");
        log.info("║  TO      : {}",  toEmail);
        log.info("║  SUBJECT : 🎉 Registration Confirmed — {}", eventName);
        log.info("╠══════════════════════════════════════════════════════╣");
        log.info("║  QR CODE CONTENT:");
        for (String line : qrContent.split("\n")) {
            log.info("║    {}", line);
        }
        log.info("╠══════════════════════════════════════════════════════╣");
        log.info("║  HTML email body rendered successfully ({} chars)", htmlBody.length());
        log.info("╚══════════════════════════════════════════════════════╝");
        log.info("\n");
    }
}
